### ISSUE TITLE
Consider WebAssembly-based dprint plugin that formats YAML

### ISSUE THREAD

**Issue by g-plane** [kachick/anylang-template#129]
I made a WebAssembly-based dprint plugin that can format YAML: https://github.com/g-plane/pretty_yaml , so we can drop process-based yamlfmt.

[dprint playground](https://dprint.dev/playground/#code/LQhQEsDsDcHtwMYFMAEaBcaUGYAsAOXbUAEwEMAXVDLFAJgAYGBGYF4O4gI3ABtfgFWJiwAycCSbNQtAObhoSSLUwBhABYAncAGcZWAGZkAtnwCeNACIBXY2U17aZEiU1IdO9PtppeUd5gAPt4+tLgArPgoAOpkvADWdsqWmgB0IaFoAMrW4FQoAMR0AJx0GVgIeRaZmABKsGZxKADyZPHlaDoUlNQqKACyAJIdKAAOsF1NKJgEDLgAbKA66uCjgsIoAFQSUqCjmrAk1ggUXrTAKCHlOvHWmTQAQgAy2MW4luUA-CgAjtZkkAoVVo5Rm5RI7gQ2lGQNgykwDzINyQFC4cV4XzG2mQmVBKAiDFSTHKJPOl1CNzu92mWGeuCI+AAEuU-gCgRRqn0UNJQhCdFDVrDICJaDlRkhNChGbBYKNyvtEL1QiJOKUiQxST5QN0AB40ejhZipXBlITdXg0+lEVLhMoIWDGYxKCieFAAPhCTx6KDIBiomkgMuUuhQXHcFHStERCFuoxQ9sBZBOKBDADkAQgzCEHnxeDonZKAAI4bD4YBEUvpIA/plugin/BYFxAcGcC4HpfAGwK4HMCWA7SA6AJuAE5Yj4CmAbrKgLRICGmZChZYAngPrv0C2iNCgAYcARhwiA7vUi8gA)

**Comment by kachick** [comment]
Thank you for the great work!

For my use, the indent of last items in list and hashmap will be removed unexpectedly, but others looks good to me 🙏

**Comment by g-plane** [comment]
Can you give me example?

**Comment by kachick** [comment]
From this repository

https://github.com/kachick/anylang-template/blob/21ac5aafbd6436a8e05ff488943f032cc47905b9/.github/workflows/ci-nix.yml#L33-L41
https://github.com/kachick/anylang-template/blob/21ac5aafbd6436a8e05ff488943f032cc47905b9/.github/workflows/merge-bot-pr.yml#L4-L8

=> https://github.com/kachick/anylang-template/actions/runs/9791270168/job/27034667182?pr=130

**Comment by g-plane** [comment]
I think it makes sense at some points. For example:

```yaml
map1:
  - 1
  - 2
# below is map2
map2:
```

We can't simply move such `# below is map2` comment into map1, but I may try to solve this in the future.

**Comment by g-plane** [comment]
v0.2.0 has been released, and this problem is fixed.

**Comment by kachick** [comment]
Thank you! 🎉 

I'll use this much useful plugin. 🙏 

---

Issued another problem for literal content as https://github.com/g-plane/pretty_yaml/issues/1
