### ISSUE TITLE
Do not depend on dprint process plugins

### ISSUE THREAD

**Issue by kachick** [kachick/anylang-template#92]
Now using https://github.com/dprint/dprint-plugin-prettier for YAML, HTML and CSS formatter
And often used https://github.com/dprint/dprint-plugin-exec to run another formatter as yamlfmt
But using dprint process plugins in NixOS needs hack https://github.com/dprint/dprint-plugin-prettier/issues/69 => https://github.com/kachick/dotfiles/pull/576#issuecomment-2081407782, I want to avoid it.

Candidates
---

* YAML: 
  * yamlfmt on vscode should consider https://github.com/kachick/times_kachick/issues/257
  * https://github.com/dprint/dprint/issues/736 => https://github.com/LeoDog896/dprint-plugin-yaml found, but looks like development phase
* CSS: https://github.com/g-plane/malva
* HTML:
  * https://github.com/malobre/dprint-plugin-html => not updated in this 2 years and the crate is archived https://github.com/malobre/hast
  * https://github.com/g-plane/markup_fmt/ # https://github.com/kachick/anylang-template/issues/92#issuecomment-2100110888

**Comment by g-plane** [comment]
Hey, to format HTML, you can use [markup_fmt](https://github.com/g-plane/markup_fmt/) which can be used as a dprint plugin.

**Comment by kachick** [comment]
I didn't know the repository, Thank you for sharing it with me! 🙏
